{% set version = "1.1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-stringmagic
  version: {{ version|replace("-", "_") }}

source:
  url: https://cran.r-project.org/src/contrib/stringmagic_{{ version }}.tar.gz
  sha256: eed1c04aa99be5a99ecfdd32498279f170e261669cc1b91d18673454064b8f8c
  #url:
  #  - {{ cran_mirror }}/src/contrib/stringmagic_{{ version }}.tar.gz
  #  - {{ cran_mirror }}/src/contrib/Archive/stringmagic/stringmagic_{{ version }}.tar.gz
  #sha256: eed1c04aa99be5a99ecfdd32498279f170e261669cc1b91d18673454064b8f8c

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]

requirements:
  build:
#    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
#    - r-rcpp                     # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
#    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("c") }}            # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
#    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base {{ rbase }}
   # - r-rcpp >=1.0.5
    - r-rcpp
  run:
    - r-base {{ rbase }}
    #- r-rcpp >=1.0.5
    - r-rcpp

test:
  commands:
    - $R -e "library('stringmagic')"           # [not win]
    - "\"%R%\" -e \"library('stringmagic')\""  # [win]

about:
  home: https://lrberge.github.io/stringmagic/
  dev_url: https://github.com/lrberge/stringmagic
  license: GPL-2.0-or-later
  summary: Performs complex string operations compactly and efficiently. Supports string interpolation jointly with over 50 string operations. Also enhances regular string functions (like grep() and co). See an introduction at <https://lrberge.github.io/stringmagic/>.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/58810
    reason: Dependency for r-dreamerr
  recipe-maintainers:
    - ianaobi
    - bkreider
  recipe-maintainers:
    - conda-forge/r
